title: Denis Perepelyuk
logo: /assets/img/selfie.jpg
description: As a final-year computer science student, I am passionate about leveraging technology to solve complex problems and create innovative solutions. Throughout my academic journey, I have honed my skills in programming, algorithm design, and software development, and I am excited to showcase my portfolio, which reflects the diverse projects and experiences that have shaped my growth as a software engineer and data scientist.
show_downloads: true
theme: jekyll-theme-minimal
